name: CnnScrapper Job

on:
  push:
    paths:
      - 'pipelines/job_units/CnnScrapper/**'

jobs:
  run-cnn-scrapper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check lint code
      run: |
        flake8 pipelines/job_units/CnnScrapper

    - name: Run tests
      run: |
        pip install pytest
        pytest pipelines/tests/cnnscrapper_test.py

    
    - name: Deploy to Databricks
      env:
        DATABRICKS_HOST: ${{ secrets.DBRX_INSTANCE }}
        DATABRICKS_TOKEN: ${{ secrets.DBRX_TOKEN }}
      run: |
        # Configure databricks-cli
        databricks configure --token --host $DATABRICKS_HOST --token $DATABRICKS_TOKEN

        # Upload your script to DBFS
        databricks fs cp pipelines/job_units/CnnScrapper/entrypoint.py dbfs:pipelines/job_units/CnnScrapper/entrypoint.py