name: CnnScrapper Job

on:
  push:
    paths:
      - 'pipelines/job_units/CnnScrapper/**'

jobs:
  run-cnn-scrapper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check lint code
      run: |
        flake8 pipelines/job_units/CnnScrapper

    - name: Run tests
      run: |
        pip install pytest
        pytest pipelines/tests/cnnscrapper_test.py

    
    - name: Install Databricks CLI
      run: pip install databricks-cli
  
    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DBRX_INSTANCE }}
        DATABRICKS_TOKEN: ${{ secrets.DBRX_TOKEN }}
      run: |
        databricks configure --token <<EOF
        $DATABRICKS_HOST
        $DATABRICKS_TOKEN
        EOF

    - name: Upload CnnScrapper directory to DBFS
      run: |
        databricks fs mkdirs dbfs:/cnn_scrapper
        databricks fs cp --recursive pipelines/job_units/CnnScrapper dbfs:/cnn_scrapper
        databricks fs cp pipelines/job_units/CnnScrapper/requirements.txt dbfs:/cnn_scrapper

    - name: Create JSON configuration file
      run: |
            echo '{
            "name": "CnnScrapperJob",
            "new_cluster": {
                "spark_version": "7.3.x-scala2.12",
                "node_type_id": "i3.xlarge",
                "num_workers": 2
            },
            "libraries": [
                {
                "pypi": {
                    "package": "dbfs:/cnn_scrapper/requirements.txt"
                }
                }
            ],
            "spark_python_task": {
                "python_file": "dbfs:/cnn_scrapper/CnnScrapper.py"
            },
            "schedule": {
                "quartz_cron_expression": "45 6 12 * * ?",
                "timezone_id": "UTC",
                "pause_status": "UNPAUSED"
            }
            }' > cnn_scrapper_job.json

    - name: Create the job on Databricks
      run: databricks jobs create --json-file cnn_scrapper_job.json