name: IndiaTVScrapper Job

on:
  push:
    paths:
      - 'pipelines/job_units/IndiaTVScrapper/**'

jobs:
  run-indiatv-scrapper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check lint code
      run: |
        black pipelines/job_units/IndiaTVScrapper

    - name: Run tests
      run: |
        pip install pytest
        pytest pipelines/tests/indiatvscrapper_test.py

    
    - name: Install Databricks CLI
      run: pip install databricks-cli
  
    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DBRX_INSTANCE }}
        DATABRICKS_TOKEN: ${{ secrets.DBRX_TOKEN }}
      run: |
        databricks configure --token <<EOF
        $DATABRICKS_HOST
        $DATABRICKS_TOKEN
        EOF

    - name: Upload IndiaTVScrapper directory to DBFS
      run: |
        databricks fs mkdirs dbfs:/indiatv_scrapper
        databricks fs cp --recursive pipelines/job_units/IndiaTVScrapper dbfs:/indiatv_scrapper

    - name: Create JSON configuration file
      run: |
        echo '{
            "name": "IndiaTVScrapperJob",
            "new_cluster": {
            "spark_version": "13.3.x-photon-scala2.12",
            "node_type_id": "Standard_DS3_v2",
            "num_workers": 8
            },
            "libraries": [
            {
                "pypi": {
                "package": "dbfs:/indiatv_scrapper/requirements.txt"
                }
            }
            ],
            "spark_python_task": {
            "python_file": "dbfs:/indiatv_scrapper/IndiaTVScrapper.py"
            },
            "schedule": {
            "quartz_cron_expression": "10 9 12 * * ?",
            "timezone_id": "UTC",
            "pause_status": "UNPAUSED"
            }
        }' > indiatv_scrapper_job.json

    - name: Create the job on Databricks
      run: databricks jobs create --json-file indiatv_scrapper_job.json